name: build laptop
on: push
jobs: 
  build-laptop:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Building a laptop"
      - run: mkdir build
      - run: touch build/computer.txt
      - run: echo "Mainboard" >> build/computer.txt
      - run: cat build/computer.txt
      - run: echo "Keyboard" >> build/computer.txt
